-- ============================================================
--  Gestão Operacional · Clientes (escolas/entidades)
--  Rode no SQL Editor. Cria a tabela de clientes e popula as
--  opções de GRE e Município (usadas no cadastro de cliente e chamado).
-- ============================================================
create table if not exists public.clientes (
  id          bigint generated always as identity primary key,
  gre         text,
  municipio   text,
  codigo_inep text,
  escola      text not null,
  created_at  timestamptz default now()
);
create index if not exists clientes_escola_idx on public.clientes (escola);
alter table public.clientes enable row level security;
drop policy if exists clientes_all_auth on public.clientes;
create policy clientes_all_auth on public.clientes for all to authenticated using (true) with check (true);

-- GRE (Gerência Regional de Educação)
insert into public.config_opcoes (campo, valor, ordem) values
  ('gre','PARNAÍBA',1),('gre','BARRAS',2),('gre','PIRIPIRI',3),('gre','TERESINA CENTRO NORTE',4),
  ('gre','CAMPO MAIOR',5),('gre','REGENERAÇÃO',6),('gre','VALENÇA',7),('gre','OEIRAS',8),
  ('gre','PICOS',9),('gre','FLORIANO',10),('gre','URUÇUÍ',11),('gre','SÃO JOÃO DO PIAUÍ',12),
  ('gre','SÃO RAIMUNDO NONATO',13),('gre','BOM JESUS',14),('gre','CORRENTE',15),('gre','FRONTEIRAS',16),
  ('gre','PAULISTANA',17),('gre','GRANDE TERESINA',18),('gre','TERESINA SUL',19),('gre','TERESINA NORDESTE',20),
  ('gre','TERESINA SUDESTE',21)
on conflict (campo, valor) do nothing;

-- Municípios
insert into public.config_opcoes (campo, valor, ordem) values
  ('municipio','PARNAÍBA',1),
  ('municipio','BOM PRINCÍPIO',2),
  ('municipio','BURITI DOS LOPES',3),
  ('municipio','CAJUEIRO DA PRAIA',4),
  ('municipio','CARAÚBAS',5),
  ('municipio','CAXINGÓ',6),
  ('municipio','COCAL',7),
  ('municipio','COCAL DOS ALVES',8),
  ('municipio','ILHA GRANDE',9),
  ('municipio','LUÍS CORREIA',10),
  ('municipio','MURICI DOS PORTELAS',11),
  ('municipio','BARRAS',12),
  ('municipio','BATALHA',13),
  ('municipio','CABECEIRAS DO PIAUÍ',14),
  ('municipio','CAMPO LARGO DO PIAUÍ',15),
  ('municipio','ESPERANTINA',16),
  ('municipio','JOAQUIM PIRES',17),
  ('municipio','JOCA MARQUES',18),
  ('municipio','LUZILÂNDIA',19),
  ('municipio','MADEIRO',20),
  ('municipio','MATIAS OLÍMPIO',21),
  ('municipio','MORRO DO CHAPÉU',22),
  ('municipio','NOSSA SENHORA DOS REMÉDIOS',23),
  ('municipio','PORTO',24),
  ('municipio','SÃO JOÃO DO ARRAIAL',25),
  ('municipio','PIRIPIRI',26),
  ('municipio','BRASILEIRA',27),
  ('municipio','DOMINGOS MOURÃO',28),
  ('municipio','LAGOA DE SÃO FRANCISCO',29),
  ('municipio','MILTON BRANDÃO',30),
  ('municipio','PEDRO II',31),
  ('municipio','PIRACURUCA',32),
  ('municipio','SÃO JOÃO DA FRONTEIRA',33),
  ('municipio','SÃO JOSÉ DO DIVINO',34),
  ('municipio','TERESINA',35),
  ('municipio','CAMPO MAIOR',36),
  ('municipio','ASSUNÇÃO DO PIAUÍ',37),
  ('municipio','BOA HORA',38),
  ('municipio','BOQUEIRÃO DO PIAUÍ',39),
  ('municipio','BURITI DOS MONTES',40),
  ('municipio','CAPITÃO DE CAMPOS',41),
  ('municipio','CASTELO DO PIAUÍ',42),
  ('municipio','COCAL DE TELHA',43),
  ('municipio','JATOBÁ DO PIAUÍ',44),
  ('municipio','JUAZEIRO DO PIAUÍ',45),
  ('municipio','NOSSA SENHORA DO NAZARÉ',46),
  ('municipio','SÃO JOÃO DA SERRA',47),
  ('municipio','SÃO MIGUEL DO TAPUIO',48),
  ('municipio','SIGEFREDO PACHECO',49),
  ('municipio','REGENERAÇÃO',50),
  ('municipio','AGRICOLÂNDIA',51),
  ('municipio','ÁGUA BRANCA',52),
  ('municipio','AMARANTE',53),
  ('municipio','ANGICAL DO PIAUÍ',54),
  ('municipio','BARRO DURO',55),
  ('municipio','HUGO NAPOLEÃO',56),
  ('municipio','JARDIM DO MULATO',57),
  ('municipio','LAGOINHA DO PIAUÍ',58),
  ('municipio','MIGUEL LEÃO',59),
  ('municipio','OLHO D''ÁGUA DO PIAUÍ',60),
  ('municipio','PASSAGEM FRANCA DO PIAUÍ',61),
  ('municipio','SANTO ANTONIO DOS MILAGRES',62),
  ('municipio','SÃO GONÇALO DO PIAUÍ',63),
  ('municipio','SÃO PEDRO DO PIAUÍ',64),
  ('municipio','VALENÇA DO PIAUÍ',65),
  ('municipio','AROAZES',66),
  ('municipio','BARRA D''ALCÂNTARA',67),
  ('municipio','ELESBÃO VELOSO',68),
  ('municipio','FRANCINÓPOLIS',69),
  ('municipio','INHUMA',70),
  ('municipio','LAGOA DO SÍTIO',71),
  ('municipio','IPIRANGA DO PIAUÍ',72),
  ('municipio','NOVO ORIENTE DO PIAUÍ',73),
  ('municipio','PIMENTEIRAS',74),
  ('municipio','SANTA CRUZ DOS MILAGRES',75),
  ('municipio','SÃO FÉLIX DO PIAUÍ',76),
  ('municipio','SÃO MIGUEL DA BAIXA GRANDE',77),
  ('municipio','VÁRZEA GRANDE',78),
  ('municipio','OEIRAS',79),
  ('municipio','CAJAZEIRAS DO PIAUÍ',80),
  ('municipio','CAMPINAS DO PIAUÍ',81),
  ('municipio','COLÔNIA DO PIAUÍ',82),
  ('municipio','FLORESTA DO PIAUÍ',83),
  ('municipio','SANTA CRUZ DO PIAUÍ',84),
  ('municipio','SANTA ROSA DO PIAUÍ',85),
  ('municipio','SANTO INÁCIO DO PIAUÍ',86),
  ('municipio','SÃO JOÃO DA VARJOTA',87),
  ('municipio','SÃO MIGUEL DO FIDALGO',88),
  ('municipio','TANQUE DO PIAUÍ',89),
  ('municipio','PICOS',90),
  ('municipio','AROEIRAS DO ITAIM',91),
  ('municipio','BOCAINA',92),
  ('municipio','DOM EXPEDITO LOPES',93),
  ('municipio','GEMINIANO',94),
  ('municipio','ITAINÓPOLIS',95),
  ('municipio','JAICÓS',96),
  ('municipio','PAQUETÁ',97),
  ('municipio','SANTANA DO PIAUÍ',98),
  ('municipio','SANTO ANTÔNIO DE LISBOA',99),
  ('municipio','SÃO JOÃO DA CANABRAVA',100),
  ('municipio','SÃO JOSÉ DO PIAUÍ',101),
  ('municipio','SÃO LUIS DO PIAUÍ',102),
  ('municipio','SUSSUAPARA',103),
  ('municipio','VERA MENDES',104),
  ('municipio','WALL FERRAZ',105),
  ('municipio','FLORIANO',106),
  ('municipio','ARRAIAL',107),
  ('municipio','CANAVIEIRA',108),
  ('municipio','FLORES DO PIAUÍ',109),
  ('municipio','FRANCISCO AYRES',110),
  ('municipio','GUADALUPE',111),
  ('municipio','ITAUEIRA',112),
  ('municipio','JERUMENHA',113),
  ('municipio','NAZARÉ DO PIAUÍ',114),
  ('municipio','PAVUSSU',115),
  ('municipio','RIO GRANDE DO PIAUÍ',116),
  ('municipio','SÃO FRANCISCO DO PIAUÍ',117),
  ('municipio','SÃO JOSÉ DO PEIXE',118),
  ('municipio','URUÇUÍ',119),
  ('municipio','ANTÔNIO ALMEIDA',120),
  ('municipio','BAIXA GRANDE DO RIBEIRO',121),
  ('municipio','BERTOLÍNIA',122),
  ('municipio','LANDRI SALES',123),
  ('municipio','MARCOS PARENTE',124),
  ('municipio','PORTO ALEGRE DO PIAUÍ',125),
  ('municipio','RIBEIRO GONÇALVES',126),
  ('municipio','SEBASTIÃO LEAL',127),
  ('municipio','SÃO JOÃO DO PIAUÍ',128),
  ('municipio','BELA VISTA DO PIAUÍ',129),
  ('municipio','BREJO DO PIAUÍ',130),
  ('municipio','CAMPO ALEGRE DO FIDALGO',131),
  ('municipio','CANTO DO BURITI',132),
  ('municipio','CAPITÃO GERVÁSIO OLIVEIRA',133),
  ('municipio','ISAÍAS COELHO',134),
  ('municipio','JOÃO COSTA',135),
  ('municipio','LAGOA DO BARRO DO PIAUÍ',136),
  ('municipio','NOVA SANTA RITA',137),
  ('municipio','PAES LANDIM',138),
  ('municipio','PAJEÚ DO PIAUÍ',139),
  ('municipio','PEDRO LAURENTINO',140),
  ('municipio','RIBEIRA DO PIAUÍ',141),
  ('municipio','SIMPLÍCIO MENDES',142),
  ('municipio','SOCORRO DO PIAUÍ',143),
  ('municipio','SÃO RAIMUNDO NONATO',144),
  ('municipio','ANISIO DE ABREU',145),
  ('municipio','BONFIM DO PIAUÍ',146),
  ('municipio','CARACOL',147),
  ('municipio','CORONEL JOSÉ DIAS',148),
  ('municipio','DIRCEU ARCOVERDE',149),
  ('municipio','DOM INOCÊNCIO',150),
  ('municipio','FARTURA DO PIAUÍ',151),
  ('municipio','GUARIBAS',152),
  ('municipio','JUREMA',153),
  ('municipio','SÃO BRAZ DO PIAUÍ',154),
  ('municipio','SÃO LOURENÇO DO PIAUÍ',155),
  ('municipio','TAMBORIL DO PIAUÍ',156),
  ('municipio','VÁRZEA BRANCA',157),
  ('municipio','BOM JESUS',158),
  ('municipio','ALVORADA DO GURGUÉIA',159),
  ('municipio','COLÔNIA DO GURGUÉIA',160),
  ('municipio','CRISTINO CASTRO',161),
  ('municipio','CURRAIS',162),
  ('municipio','ELISEU MARTINS',163),
  ('municipio','MANOEL EMÍDIO',164),
  ('municipio','PALMEIRA DO PIAUÍ',165),
  ('municipio','REDENÇÃO DO GURGUÉIA',166),
  ('municipio','SANTA LUZ',167),
  ('municipio','CORRENTE',168),
  ('municipio','AVELINO LOPES',169),
  ('municipio','BARREIRAS DO PIAUÍ',170),
  ('municipio','CRISTALÂNDIA DO PIAUÍ',171),
  ('municipio','CURIMATÁ',172),
  ('municipio','GILBUÉS',173),
  ('municipio','JÚLIO BORGES',174),
  ('municipio','MONTE ALEGRE DO PIAUÍ',175),
  ('municipio','MORRO CABEÇA NO TEMPO',176),
  ('municipio','PARNAGUÁ',177),
  ('municipio','RIACHO FRIO',178),
  ('municipio','SANTA FILOMENA',179),
  ('municipio','SÃO GONÇALO DO GURGUÉIA',180),
  ('municipio','SEBASTIÃO BARROS',181),
  ('municipio','FRONTEIRAS',182),
  ('municipio','ALAGOINHA DO PIAUÍ',183),
  ('municipio','ALEGRETE DO PIAUÍ',184),
  ('municipio','BELÉM DO PIAUÍ',185),
  ('municipio','CALDEIRÃO GRANDE DO PIAUÍ',186),
  ('municipio','CAMPO GRANDE DO PIAUÍ',187),
  ('municipio','FRANCISCO MACEDO',188),
  ('municipio','FRANCISCO SANTOS',189),
  ('municipio','MARCOLÂNDIA',190),
  ('municipio','MONSENHOR HIPÓLITO',191),
  ('municipio','PADRE MARCOS',192),
  ('municipio','PIO IX',193),
  ('municipio','SÃO JULIÃO',194),
  ('municipio','SIMÕES',195),
  ('municipio','VILA NOVA DO PIAUÍ',196),
  ('municipio','PAULISTANA',197),
  ('municipio','ACAUÃ',198),
  ('municipio','BETÂNIA DO PIAUÍ',199),
  ('municipio','CARIDADE DO PIAUÍ',200),
  ('municipio','CONCEIÇÃO DO CANINDÉ',201),
  ('municipio','CURRAL NOVO DO PIAUÍ',202),
  ('municipio','JACOBINA DO PIAUÍ',203),
  ('municipio','MASSAPÊ DO PIAUÍ',204),
  ('municipio','PATOS DO PIAUÍ',205),
  ('municipio','QUEIMADA NOVA',206),
  ('municipio','SÃO FRANCISCO DE ASSIS DO PIAUÍ',207),
  ('municipio','ALTO LONGÁ',208),
  ('municipio','ALTOS',209),
  ('municipio','BENEDITINOS',210),
  ('municipio','COIVARAS',211),
  ('municipio','CURRALINHOS',212),
  ('municipio','DEMERVAL LOBÃO',213),
  ('municipio','JOSÉ DE FREITAS',214),
  ('municipio','LAGOA ALEGRE',215),
  ('municipio','LAGOA DO PIAUÍ',216),
  ('municipio','MIGUEL ALVES',217),
  ('municipio','MONSENHOR GIL',218),
  ('municipio','NAZÁRIA',219),
  ('municipio','NOVO SANTO ANTÔNIO',220),
  ('municipio','PALMEIRAIS',221),
  ('municipio','PAU D''ARCO DO PIAUÍ',222),
  ('municipio','PRATA DO PIAUÍ',223),
  ('municipio','UNIÃO',224)
on conflict (campo, valor) do nothing;
